### ISSUE TITLE
Modifications to run with Python 3.8 / TensorFlow 2.x ?

### ISSUE THREAD

**Issue by grahamwhaley** [ag1le/deepmorse-decoder#23]
Hi @ag1le ,
 I was interested in giving this code a spin. I have a general interest in morse decoding, and wanted something to test out on my linux desktop akin to running CW Skimmer - this looked promising.

However, I'm on an Ubuntu 20 system, and that comes with Python 3.8, which then forces a library bump to TensorFlow 2.x, which then runs into some TF problems.

I'm not really expecting you to leap on this, as it looks like this experimental codebase is not active, but if you have any quick fix insights or code that would be great ;-) Otherwise, I'll leave the info here for any others in the future who run into the issues.

First off, I had to do some updates to `requirements.txt`. The `dataclasses` is now built in to Python 3.8, so is not required, but causes errors if still in the requirements file :-( And then I needed to bump tensorflow, as v1.x is not supported with Python 3.8 on ubuntu:

```patch
diff --git a/requirements.txt b/requirements.txt
index 7af6589..0ca28bb 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -7,7 +7,6 @@ certifi==2020.4.5.1
 chardet==3.0.4
 click==7.1.1
 cycler==0.10.0
-dataclasses==0.7
 deprecation==2.0.7
 editdistance==0.5.2
 entrypoints==0.3
@@ -55,7 +54,7 @@ six==1.14.0
 sklearn==0.0
 strsimpy==0.1.4
 tensorboard==1.15.0
-tensorflow==1.15.2
+tensorflow==2.11
 tensorflow-estimator==1.14.0
 termcolor==1.1.0
 toml==0.10.0
```

I had to fix the `yaml.loader()` call, as a `Loader=` argument is now mandatory for safety reasons:

```patch
--- a/morse/MorseDecoder.py
+++ b/morse/MorseDecoder.py
@@ -36,7 +36,8 @@ class Config():
 
     def __init__(self, file_name): 
         with open(file_name) as f:
-            self.config = yaml.load(f.read())
+            self.config = yaml.load(f.read(), Loader=yaml.FullLoader)
+#            self.config = yaml.load(f.read())
```

Then I had to disable `tf` eager execution, as that is now on by default but this code is was not written to use that feature:

```patch
@@ -848,6 +849,12 @@ class Model:
         self.mustRestore = mustRestore
         self.snapID = 0
 
+        # Disable eager execution as this is tf V1 code
+        #tf.compat.v1.disable_eager_execution()
+        from tensorflow.python.framework.ops import disable_eager_execution
+        disable_eager_execution()
+
         # input image batch
         self.inputImgs = tf.compat.v1.placeholder(tf.float32, shape=(None, self.imgSize[0], self.imgSize[1]))
```

And finally, it looks like the `tf.contrib.rnn` is no longer an option for TF 2.x, but there is a replacement/equivalent in the `keras` system. Here is where I fell down - it looks like the function arguments are different, and I don't know how to substitute in the new library. Here is my initial dumb stab at it, and the resulting error. Any help appreciated.

```patch
@@ -896,7 +903,9 @@ class Model:
         # basic cells which is used to build RNN
         numHidden = 256
    
-        cells = [tf.contrib.rnn.LSTMCell(num_units=numHidden, state_is_tuple=True) for _ in range(2)] # 2 layers
+        # contrib deprecated in tf V2
+        #cells = [tf.contrib.rnn.LSTMCell(num_units=numHidden, state_is_tuple=True) for _ in range(2)] # 2 layers
+        cells = [tf.keras.layers.LSTMCell(num_units=numHidden, state_is_tuple=True) for _ in range(2)] # 2 layers
```

and the error at runtime:

```bash
  File "specgram.py", line 240, in <module>
    main()
  File "specgram.py", line 182, in main
    model = Model(
  File "/home/gwhaley/go/src/github.com/ag1le/deepmorse-decoder/morse/MorseDecoder.py", line 863, in __init__
    self.setupRNN()
  File "/home/gwhaley/go/src/github.com/ag1le/deepmorse-decoder/morse/MorseDecoder.py", line 908, in setupRNN
    cells = [tf.keras.layers.LSTMCell(num_units=numHidden, state_is_tuple=True) for _ in range(2)] # 2 layers
  File "/home/gwhaley/go/src/github.com/ag1le/deepmorse-decoder/morse/MorseDecoder.py", line 908, in <listcomp>
    cells = [tf.keras.layers.LSTMCell(num_units=numHidden, state_is_tuple=True) for _ in range(2)] # 2 layers
TypeError: __init__() missing 1 required positional argument: 'units'
```

I'm afraid I'm not very Python or TF savvy, so without a lot of effort I'm a bit stuck at that point. many thanks!
 Graham, M7GRW

**Comment by grahamwhaley** [comment]
Ah, it looks like maybe one of the forks of this repo has done some work on this already:
https://github.com/lsaca05/deepmorse-decoder/pull/1
@lsaca05 - any thoughts?

**Comment by ag1le** [comment]
Hi Graham

I haven't touched this experimental code base for several years, so it is
definitely outdated.

I did this hobby project to learn how these ML algorithms work, and had no
intention to build a product or charge any money from anybody for this.
Unfortunately I'm
not able to put time on fixing any incompatibility issues.

I hope you understand and find the repo useful for your purposes.

73
Mauri AG1LE

**Comment by grahamwhaley** [comment]
OK, no problem @ag1le , understood. I managed to take the fork from @lsaca05 and apply the below patch to update some deps and got the app to run. The spectrum seems to be doing OK at picking out the morse dits and dahs, but the text decode window doesn't seem to be decoding the text properly - it feels like it is decoding 'too fast'.

I'll leave it there in case somebody else wants to pick it up in the future, and will close this Issue. Thanks for responding!

```patch
diff --git a/dummy.png b/dummy.png
index bc5517e..d1918a7 100644
Binary files a/dummy.png and b/dummy.png differ
diff --git a/requirements.txt b/requirements.txt
index 5476627..0ed6a52 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,4 +1,4 @@
-absl-py==0.9.0
+absl-py==1.0.0
 appdirs==1.4.3
 astor==0.8.1
 attrs==19.3.0
@@ -7,7 +7,6 @@ certifi==2020.4.5.1
 chardet==3.0.4
 click==7.1.1
 cycler==0.10.0
-dataclasses==0.7
 deprecation==2.0.7
 editdistance==0.5.2
 entrypoints==0.3
@@ -29,7 +28,7 @@ Markdown==3.2.1
 matplotlib==3.2.1
 mccabe==0.6.1
 mock==4.0.2
-numpy==1.18.2
+numpy==1.22.0
 opencv-python==4.2.0.34
 opt-einsum==3.2.0
 packaging==20.3
@@ -54,13 +53,13 @@ scipy==1.4.1
 six==1.14.0
 sklearn==0.0
 strsimpy==0.1.4
-tensorboard==1.15.0
-tensorflow==1.15.2
-tensorflow-estimator==1.14.0
+tensorboard==2.11
+tensorflow==2.11
+tensorflow-estimator==2.11
 termcolor==1.1.0
 toml==0.10.0
 typed-ast==1.4.1
 urllib3==1.25.8
 Werkzeug==1.0.1
 wrapt==1.12.1
-wxPython==4.0.7.post2
\ No newline at end of file
+wxPython==4.0.7.post2
```

Graham, M7GRW
